// @ts-check
/**
 * ESLint flat config — single root config, applied to every workspace.
 *
 * Layered as :
 *   1. Global ignores (build artefacts, generated code).
 *   2. JS recommended (always-on baseline).
 *   3. TypeScript recommended (no type-aware mode yet — opt in per
 *      package once the legacy JSX islands of Tier A.2 are migrated).
 *   4. React + react-hooks + react-refresh + jsx-a11y on JSX/TSX
 *      surfaces (web only).
 *   5. Project-specific rules drawn from CLAUDE.md (no `any`, no raw
 *      `crypto.subtle` outside `core/crypto/`, no `console.log` in
 *      api code, etc.).
 *   6. Per-island overrides : legacy `.jsx` files are linted in a
 *      relaxed mode so we get the React/a11y signal without being
 *      blocked on the deeper TS strictness.
 *   7. Test files relax a couple of rules (we do `expect(x as any)`
 *      pinpoint casts in some Vitest fixtures).
 */

import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import importX from 'eslint-plugin-import-x';
import globals from 'globals';

export default tseslint.config(
  // ── 1. Global ignores ──────────────────────────────────────────
  {
    ignores: [
      '**/dist/**',
      '**/build/**',
      '**/coverage/**',
      '**/node_modules/**',
      '**/.vite/**',
      'packages/api/drizzle/**',
      // Auto-generated by build, not source.
      'packages/web/dist/**',
    ],
  },

  // ── 2. JS baseline ─────────────────────────────────────────────
  js.configs.recommended,

  // ── 3. TypeScript ──────────────────────────────────────────────
  ...tseslint.configs.recommended,

  // ── 4. React surface (JSX/TSX) ────────────────────────────────
  {
    files: ['packages/web/**/*.{jsx,tsx}'],
    plugins: {
      react,
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
      'jsx-a11y': jsxA11y,
    },
    languageOptions: {
      globals: { ...globals.browser },
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    settings: {
      react: { version: '19.1.1' },
    },
    rules: {
      ...react.configs.recommended.rules,
      ...react.configs['jsx-runtime'].rules,
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.configs.recommended.rules,
      // React 17+ JSX transform — `import React` not required.
      'react/react-in-jsx-scope': 'off',
      // PropTypes are dead in a TS-first project — we type via
      // interfaces. Leaving this on fires noise on the legacy
      // .jsx islands without surfacing real signal.
      'react/prop-types': 'off',
      // The default `forbid` list includes `'` and `"`, which
      // floods FR copy with false positives — apostrophes are
      // benign in JSX text content. Keep the rule for the
      // genuinely dangerous characters (`<`, `>`, `}`) so that
      // an accidental `<3` or stray `}` still fires.
      'react/no-unescaped-entities': ['error', { forbid: ['<', '>', '}'] }],
      // Wrapped-label is acceptable, but the rule needs to know
      // which custom components are controls (otherwise it sees
      // <Input/> as opaque JSX and complains).
      'jsx-a11y/label-has-associated-control': [
        'error',
        {
          assert: 'either',
          depth: 3,
          controlComponents: [
            'Input',
            'Textarea',
            'Select',
            'DirkInput',
            'DirkTextarea',
            'DirkSelect',
          ],
        },
      ],
      // `interface Foo extends Bar {}` is intentional for
      // branded-type aliases and Hono context shims — disable
      // the empty-object-type complaint there.
      '@typescript-eslint/no-empty-object-type': [
        'error',
        { allowInterfaces: 'with-single-extends' },
      ],
      // Vite/Fast Refresh — only-export-components warns when a
      // module exports both a component and a constant; we ship a
      // few of those (e.g. context modules) so leave it as warn,
      // not error.
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
      // JSX-A11y default exemptions for the autoFocus rule are
      // overridden here — autofocus is fine on a freshly opened
      // modal where the form would be the only target anyway.
      // We use it deliberately in the composer modals.
      'jsx-a11y/no-autofocus': 'off',
    },
  },

  // ── 5. Project-specific rules (from CLAUDE.md) ─────────────────
  {
    files: ['packages/**/*.{ts,tsx}'],
    plugins: { 'import-x': importX },
    rules: {
      // CLAUDE.md : « `any` is forbidden in new code »
      '@typescript-eslint/no-explicit-any': 'error',
      // Aliasing `unknown` to `any` defeats the rule above.
      '@typescript-eslint/no-unsafe-argument': 'off',
      // Allow `_var` for intentionally-unused.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // Import hygiene — duplicates and circulars are dead-weight
      // signals, not just style.
      'import-x/no-duplicates': 'error',
      // `ignoreExternal` keeps cycle detection inside our own code and
      // stops the resolver from walking `node_modules` packages — some
      // (e.g. the `read-excel-file` / `write-excel-file` subpath-`exports`
      // builds) crash import-x's default resolver. We never police cycles
      // through a third-party dependency anyway.
      'import-x/no-cycle': ['warn', { maxDepth: 5, ignoreExternal: true }],
    },
  },

  // CLAUDE.md : « Never log, persist, or expose a `CryptoKey` ».
  // The single source for AES / HMAC / key derivation is
  // `core/crypto/`. Touching `crypto.subtle.*` outside that path
  // is a red flag — prefer the helpers. We deliberately allow
  // bare `crypto.randomUUID()` and `crypto.getRandomValues()`
  // (no key material involved, just IDs / nonces) so the rule
  // targets the .subtle member path specifically rather than the
  // entire `crypto` global.
  {
    files: ['packages/web/src/**/*.{ts,tsx}'],
    ignores: [
      'packages/web/src/core/crypto/**',
      'packages/web/src/**/*.test.{ts,tsx}',
    ],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector:
            "MemberExpression[object.name='crypto'][property.name='subtle']",
          message:
            'Use helpers in `core/crypto/` (deriveKey, encryptJson, …) instead of touching `crypto.subtle` directly. CLAUDE.md §Crypto rule 3.',
        },
      ],
    },
  },

  // CLAUDE.md : « No `console.log` côté api (utiliser Pino) ».
  {
    files: ['packages/api/src/**/*.ts'],
    ignores: [
      'packages/api/src/seed/**',
      'packages/api/src/seed.ts',
      'packages/api/src/db/migrate.ts',
      'packages/api/src/db/migrate-test.ts',
    ],
    rules: {
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },

  // ── 6. Legacy JSX islands (Tier A.2 of health.md) ──────────────
  // 18 files left in packages/web/src/. We surface their React /
  // a11y issues without blocking on the TS strictness they can't
  // satisfy until they're migrated.
  {
    files: ['**/*.{js,jsx,mjs,cjs}'],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-require-imports': 'off',
    },
  },

  // ── 7. Test files ──────────────────────────────────────────────
  {
    files: ['**/*.test.{ts,tsx}', '**/*.spec.{ts,tsx}', '**/test/**'],
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      'no-console': 'off',
      'react-refresh/only-export-components': 'off',
    },
  },

  // ── 8. Config & build files ────────────────────────────────────
  {
    files: [
      '**/*.config.{ts,mts,cts,js,mjs,cjs}',
      'eslint.config.mjs',
      'vite.config.{js,ts}',
      'vitest.config.{js,ts}',
      'drizzle.config.ts',
    ],
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      'no-console': 'off',
    },
  },
);
