/**
 * Canonical list of machine error codes the API returns in its
 * `{ error, reason? }` payload on non-OK responses.
 *
 * The union is **non-exhaustive on purpose** — front code uses
 * `KnownApiErrorCode | (string & {})` so :
 *
 *   1. Auto-complete surfaces every known code.
 *   2. Adding a new code on the API side doesn't break the
 *      front type check (the message will fall back to the
 *      generic « unknown » entry until i18n catches up).
 *   3. The runtime guard `isKnownApiErrorCode` lets call sites
 *      narrow when they need to.
 *
 * The list is generated by grepping `{ error: 'xxx' }` in
 * `packages/api/src/routes/`. Keep it sorted alphabetically and
 * add a comment block when intent is non-obvious.
 *
 * Reference: `docs/roadmap/health.md` Tier B.4.
 */

export const KNOWN_API_ERROR_CODES = [
  // ── auth — credentials / state ──────────────────────────────
  'account_not_activated',
  'invalid_credentials',
  'invalid_token',
  'multi_factor_loss',
  'passkey_required',
  'second_factor_required',
  'totp_required',
  'unauthenticated',

  // ── auth — TOTP / passkey enrolment ─────────────────────────
  'already_enabled',
  'already_enrolled',
  'backup_codes_unacknowledged',
  'challenge_expired',
  'factor_not_required',
  'invalid_code',
  'no_pending_challenge',
  'no_pending_enrollment',
  'totp_not_enabled',
  'user_verification_required',
  'verification_failed',

  // ── auth — register / activate / recover ────────────────────
  'activation_failed',
  'email_send_failed',
  'email_taken',
  'register_failed',
  'registration_closed',
  'user_already_exists',

  // ── auth — MFA bypass ───────────────────────────────────────
  'bypass_already_active',

  // ── admin / authorization ───────────────────────────────────
  'cannot_delete_self',
  'forbidden',

  // ── module / collection guard layer ─────────────────────────
  'guard_already_promoted',
  'guard_mismatch',
  'missing_guard_params',
  'missing_id',
  'missing_sid',
  'not_found',
  'not_found_or_used',

  // ── input validation ────────────────────────────────────────
  'invalid_body',
  'invalid_url',
  'no_body',
  'too_large',

  // ── upload / fetch helpers ──────────────────────────────────
  'fetch_failed',
  'host_not_allowed',
  'https_required',
  'lookup_failed',
  'missing_url',
  'not_an_image',

  // ── transport ───────────────────────────────────────────────
  'rate_limited',

  // ── catch-all server failures ───────────────────────────────
  'insert_failed',
  'internal',
  'internal_error',
  'update_failed',
] as const;

/**
 * Set form for the `KnownApiErrorCode` array — used by the runtime
 * guard. `as ReadonlySet<string>` so callers can `.has(unknown)`
 * without an extra cast.
 */
const KNOWN_CODES_SET: ReadonlySet<string> = new Set(KNOWN_API_ERROR_CODES);

/** Compile-time union of every recognised code. */
export type KnownApiErrorCode = (typeof KNOWN_API_ERROR_CODES)[number];

/**
 * Permissive alias used in API response shapes. The `& {}` part keeps
 * IDE autocomplete on `KnownApiErrorCode` while not blocking strings
 * that ship without a frontend translation yet.
 */
export type ApiErrorCode = KnownApiErrorCode | (string & {});

export function isKnownApiErrorCode(value: string): value is KnownApiErrorCode {
  return KNOWN_CODES_SET.has(value);
}
